# syntax=docker/dockerfile:1

FROM node:20-slim as base

LABEL fly_launch_runtime="Bun"

RUN npm install -g bun

# Set production environment
ENV NODE_ENV="production"

WORKDIR /app

# Install node modules
COPY --link bun.lockb package.json ./

RUN bun install --ci

# Copy application code
COPY --link . .

RUN bun tailwind:prod

RUN bun build-js:prod

COPY --link . .

CMD ["bun", "run", "src/index.tsx"]
