# syntax=docker/dockerfile:1

FROM node:20-slim as base

LABEL fly_launch_runtime="Bun"

RUN npm install -g bun

WORKDIR /app

# Install node modules
COPY --link bun.lockb package.json ./

RUN bun install

ENV SERVER_PORT 3000
EXPOSE $SERVER_PORT

CMD ["bun", "run", "start:dev"]
