version: '3.9'
services:
  app:
    build:
      context: .
      # target: production
      dockerfile: Dockerfile.production
    env_file:
      - .env.production
    ports:
      - 3001:3001
    volumes:
      - ./:/app
      - /app/node_modules
    # depends_on:
    #   - mongo
    # networks:
    #   - node-network

  dev:
    build:
      context: .
      # target: development
      dockerfile: Dockerfile.development
    env_file:
      - .env.development
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - node-network

  mongo:
    image: mongo:latest
    container_name: mongo_dev
    env_file:
      - .env.development
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - node-network

volumes:
  mongo-data:
    driver: local

networks:
  node-network:
    driver: bridge